USE CARTILLA;

SELECT * FROM USUARIO;
SELECT * FROM CLIENTE;
SELECT * FROM PRODUCTOS;
SELECT * FROM CARRITO
SELECT * FROM DETALLES_PEDIDOS;
SELECT * FROM PEDIDOS;

TRUNCATE TABLE PEDIDOS;
TRUNCATE TABLE CARRITO;
TRUNCATE TABLE PRODUCTOS;
TRUNCATE TABLE USUARIO;
TRUNCATE TABLE CLIENTE;
TRUNCATE TABLE DETALLES_PEDIDOS
TRUNCATE TABLE SESIONES_T;
TRUNCATE TABLE SESIONES_CMS_T;

DROP TABLE USUARIO;
DROP TABLE CLIENTE;
DROP TABLE PRODUCTOS;
DROP TABLE CARRITO;
DROP TABLE PEDIDOS;
DROP TABLE DETALLES_PEDIDOS;

select [dbo].[OBTENER_FECHA]()

insert into usuario(CORREO_US,CONTRASEÑA_US,puesto) values('leonard.cantulara@hotmail.com','1234','Militar')
