CREATE DATABASE CARTILLA;
USE CARTILLA;

CREATE TABLE USUARIO(
    ID_US INT IDENTITY(1,1),
    FECHA_ALTA_US DATETIME,
    CORREO_US VARCHAR(100),
    CONTRASEÑA_US VARCHAR(50),
    NOMBRE_US VARCHAR(200),
    ACTIVO_US BIT,
    PUESTO VARCHAR(50),
	TELEFONO VARCHAR(50),
	DIRECCION_US VARCHAR(600),
	RFC VARCHAR(20),
	CODIGO_US VARCHAR(20),
    PRIMARY KEY(ID_US)
    
);

CREATE TABLE CLIENTE (
  ID_CLI INT IDENTITY(1,1),
  FECHA_ALTA_CLI DATETIME,
  ACTIVO_CLI BIT,
  NOMBRE_CLI VARCHAR(600),
  CORREO_CLI VARCHAR(600),
  CONTRASEÑA_CLI VARCHAR(600),
  CODIGO_VERIF_CLI INT,
  DOBLE_AUT_CLI BIT,
  PRIMARY KEY (ID_CLI)
);
ALTER TABLE CLIENTE ADD CIUDAD VARCHAR(8)
CREATE TABLE PRODUCTOS (
  ID_PRO INT IDENTITY(1,1),
  NOM_PRO VARCHAR(600)NOT NULL UNIQUE,
  FECHA_ALTA_PRO DATETIME,
  CANT_PRO INT,
  DESC_PRO VARCHAR(600),
  PRECIO_PRO DECIMAL(10,2),
  COLOR_PRO VARCHAR(100),
  MARCA_PRO VARCHAR(600),
  ACT_PRO BIT,
  GEN_PRO VARCHAR(600),
  PT_IMG VARCHAR(600),
  TIPO_PRO VARCHAR(600),
  PRIMARY KEY (ID_PRO)
);
CREATE TABLE CARRITO(
    ID_CLI INT NOT NULL,
    ID_PRO INT NOT NULL,
    PAGO_TOT DECIMAL(10,2),
    CANT_PRO INT,
	PAGO_TOT_PRODUCTOS DECIMAL(10,2)
    CONSTRAINT FK_CLIENTE_CARRITO FOREIGN KEY (ID_CLI) REFERENCES CLIENTE(ID_CLI),
    CONSTRAINT FK_PRODUCTOS_CARRITO FOREIGN KEY (ID_PRO) REFERENCES PRODUCTOS(ID_PRO)
);
CREATE TABLE DETALLES_PEDIDOS (
  ID_DET_PED INT IDENTITY(1,1) PRIMARY KEY,
  PEDIDO_ID INT,
  ID_PRO INT NOT NULL,
  CANTIDAD_PRO INT,
  PRECIO_UNITARIO DECIMAL(10,2),
  DIRECCION VARCHAR(100) NOT NULL,
  ESTADO VARCHAR(100),
  CIUDAD VARCHAR(100),
  COD_POSTAL VARCHAR(30),
  TELEFONO VARCHAR(30)
);
CREATE TABLE PEDIDOS(
    ID_PED INT PRIMARY KEY IDENTITY(1,1),
    CLIENTE_ID INT NOT NULL,
    FECHA_PED DATETIME,
    ESTADO_PED VARCHAR(50),
    PAGO_TOT DECIMAL(10,2)
);